### PR TITLE
use bemxjst 4.2.7 & lazy require

### PR DESCRIPTION
**Pull request by sbmaxx**

### CODE REVIEW

**Comment by tadatuta** [comment]
There's already `4.2.7` since https://github.com/enb-bem/enb-bemxjst/releases/tag/v4.0.1 (https://github.com/enb-bem/enb-bemxjst/commit/d6a2337924acf3b8a5a15c67bf1e96316703bca9)

**Comment by sbmaxx** [comment]
hm, ok. just "lazy require" :)

**Comment by tadatuta** [comment]
diff looks like you should rebase your branch, isn't it?
and please fix codestyle (see https://travis-ci.org/enb-bem/enb-bemxjst/jobs/93108525)

**Comment by blond** [comment]
Closed favor of #115

**Comment by blond** [comment]
Fixed in `v4.0.2`.

**Pull request closed without merging**
